name = "Tupa"
version = "0.0.1"
license = "GPL"
author = "Carlos Kleber C. Arruda"
maintainer = "carloskleber@gmail.com"
copyright = "Copyright 2026, Carlos Kleber"
dependencies.stdlib = "*"
dependencies.feh = { git = "https://github.com/samharrison7/fortran-error-handler" }

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["lapack", "blas"]
external-modules = ["slatec"]
# To be considered: json-fortran, quadpack

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[example]]
name = "example1"
main = "example1.f90"

